---
title: "SavageScores"
author: "Mango117"
date: "2 March 2023"
output: savage scores
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(readxl)
library(plyr)
library(dplyr)
```


```{r}
concord<-function (data,n,s=0){
  'This function includes the tie corrections'
  m0<-as.matrix(data)
  nc<-ncol(m0)
  if(n<2){stop("Incorrect input for n")}
  if(nc>n){
    ncg<-rep(n+1:nc)
    m<-m0[,-ncg]
  }
  else{ if(nc==n){
    m<-m0
  }
    else{stop("Please check the number of variables and the entered value for n and re-run.")}
    
  }
  
  m2<-m[order(m[,1], decreasing = FALSE),]
  
  m1<-matrix(1:1,dim(data)[1],dim(data)[1])
  v<-array(0,dim(data)[1])
  v1<-array(0,dim(data)[1])
  v2<-array(0,dim(data)[1])
  v3<-array(0,dim(data)[1])
  Ti<-array(0,dim(data)[1])
  m1[lower.tri(m1)]<-0
  
  v2<-c(1:dim(data)[1])
  m3<-1/v2 
  savage<-matrix(0:0,dim(data)[1],n)
  m4<-matrix(0:0,dim(data)[1],2*n)
  m4[,1:n]<-m2
  for (i in 1:n){
    if (s == 0) {
      v2<-m3
      v3<-sort(v2,decreasing=TRUE)
      v<-m1%*%v3
      od<-order(m2[,i])
      v1<-v[order(od)]
      m4[,i+n]<-v1} 
    
    if (s ==1){ 
      v3<-v2
      v<-v3
      od<-order(m2[,i])
      v1<-v[order(od)]
      m4[,i+n]<-v1 
    }
    kmpbind<-data.frame(cbind(group=m4[,i],cc=m4[,i+n]))
    kmpcount<-data.frame(ddply(kmpbind,.(group),summarize,mean=mean(cc)))
    group<-data.frame(group=m4[,i])
    
    kmp<-left_join(group,kmpcount, by= 'group')
    savage[,i]<-kmp$mean
    savagesum<-apply(savage,1,sum)
    savagesumsq<-(savagesum^2)
    savagesumsqr<-sum(savagesumsq)
    counter<-data.frame(ddply(kmpbind,.(group),summarize,N=length(cc)))
    Ti[i]<- sum(((counter[,2])^3-counter[,2]))
    Ticor<-sum(Ti)
    c1<-1/(n^2*(dim(data)[1]-savage[1,1]))
    c2<-(savagesumsqr-n^2*dim(data)[1])
    df<-as.numeric(as.numeric(length(savagesum))-1)
    if (n >2) { if(s==0){rt<-"Not defined for more than 2 variables"
    Ct<-as.numeric(c1*c2)
    Ctt<-n*(dim(data)[1]-1)*as.numeric(c1*c2)
    pr<-pchisq(Ctt, df,lower.tail=FALSE)}}
    if(s==1){rt<-"Not defined for more than 2 variables"
    U<-12*(savagesumsqr)-3*n^2*(dim(data)[1])*((dim(data)[1])+1)^2
    Ct<-U/((n^2*(dim(data)[1])*(((dim(data)[1])^2)-1))-(n*Ticor))
    Ctt<-n*(dim(data)[1]-1)*Ct
    pr<-pchisq(Ctt, df,lower.tail=FALSE)}
    if (n ==2) {
      if(s==0) {
        Ct<-"Not defined for 2 variables"
        rt<-(sum(savage[,1]*savage[,2])-dim(data)[1])/(dim(data)[1]-savage[1,1])
        if(dim(data)[1]<200){rz<-rt*(dim(data)[1]-2)^0.5/(1-rt^2)^0.5
        df<-dim(data)[1]-2
        pr<-pt(rz, df=df, lower.tail = FALSE)}
        if(dim(data)[1]>=200){rz<-rt*(dim(data)[1]-1)^0.5
        pr<-pnorm(rz, mean = 0, sd = 1, lower.tail = FALSE)}
      }
      else{ Ct<-"Not defined for 2 variables"
      d2<-sum((savage[,1]-savage[,2])^2)
      x2<-(((dim(data)[1]^3-(dim(data)[1]))) -Ti[1])/12
      y2<-(((dim(data)[1]^3-(dim(data)[1]))) -Ti[2])/12
      rt<-(x2+y2-d2)/(2*sqrt(x2*y2))
      if(dim(data)[1]<200){rz<-rt*(dim(data)[1]-2)^0.5/(1-rt^2)^0.5
      df<-dim(data)[1]-2
      pr<-pt(rz, df=df, lower.tail = FALSE)}
      if(dim(data)[1]>=200){rz<-rt*(dim(data)[1]-1)^0.5
      pr<-pnorm(rz, mean = 0, sd = 1, lower.tail = FALSE)}
      }
    }
  }
  print("The following list outputs the data used, correlation or Tau value and the associated one tail probabilities (non-exact)")
  print(list(Scores=savage,Tau=Ct, Corr= rt,df=df,Probabilty=pr))
}
```

```{r}
excel <- read_excel("/Users/manojarachige/Library/CloudStorage/Dropbox/Mac/Documents/Coding/Projects/BMedScDOC2021/BMedScDOC_2023/Book1.xlsx")
```

```{r}
concord(excel,4,s=0)
```

